using System.Text;
using System.Text.RegularExpressions;
using Microsoft.Data.Sqlite;
using VibeRails.Data.Sqlite;
using Xunit;

namespace Tests.DB;

/// <summary>
/// docs/schema/*.sql is the reviewable form of every table this code creates. A table change
/// shows up there as a diff the owner signs off on, instead of hiding inside C# string constants.
/// Regenerate deliberately: set VIBE_RAILS_UPDATE_SCHEMA_SNAPSHOT=1 and run this class.
/// </summary>
public sealed class SchemaSnapshotTests
{
    private const string UpdateVariable = "VIBE_RAILS_UPDATE_SCHEMA_SNAPSHOT";
    private const string Header =
        "-- Generated by Tests/DB/SchemaSnapshotTests.cs from an empty database. Do not edit by hand.\n" +
        "-- Regenerate: set VIBE_RAILS_UPDATE_SCHEMA_SNAPSHOT=1, then: dotnet test Tests --filter SchemaSnapshotTests\n" +
        "-- Every diff in this file is a table change and needs the owner's sign-off (vibe-data/docs/db-migration-policy.md).\n\n";

    [Fact]
    public void CheckedInSchemaMatchesWhatTheStoresCreate()
    {
        Assert.SkipUnless(OperatingSystem.IsWindows(), "One JobRuns index is named per OS; the snapshot is generated on Windows.");
        var root = RepositoryRoot();
        var directory = Path.Combine(Path.GetTempPath(), "viberails-schema-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(directory);
        try
        {
            var statePath = Path.Combine(directory, "state.db");
            var proxyPath = Path.Combine(directory, "proxy_exchanges.db");
            SqliteStorage.EnsureAllSchemas(new SqliteStoragePaths(statePath, null, proxyPath));
            AssertSnapshot(root, "state.sql", Dump(statePath));
            AssertSnapshot(root, "proxy_exchanges.sql", Dump(proxyPath));
        }
        finally
        {
            SqliteConnection.ClearAllPools();
            try { Directory.Delete(directory, true); } catch (IOException) { }
        }
    }

    private static void AssertSnapshot(string root, string fileName, string actual)
    {
        var path = Path.Combine(root, "docs", "schema", fileName);
        if (Environment.GetEnvironmentVariable(UpdateVariable) == "1")
        {
            Directory.CreateDirectory(Path.GetDirectoryName(path)!);
            File.WriteAllText(path, actual);
            return;
        }
        Assert.True(File.Exists(path), $"Missing schema snapshot {path}. Generate it with {UpdateVariable}=1 and have the owner review it.");
        var expected = File.ReadAllText(path).Replace("\r\n", "\n");
        if (expected == actual)
            return;
        var expectedLines = expected.Split('\n');
        var actualLines = actual.Split('\n');
        var first = Enumerable.Range(0, Math.Max(expectedLines.Length, actualLines.Length))
            .First(i => i >= expectedLines.Length || i >= actualLines.Length || expectedLines[i] != actualLines[i]);
        Assert.Fail(
            $"The schema the stores create no longer matches {path} (first difference at line {first + 1}).\n" +
            $"  snapshot: {(first < expectedLines.Length ? expectedLines[first] : "<end of file>")}\n" +
            $"  actual:   {(first < actualLines.Length ? actualLines[first] : "<end of file>")}\n" +
            $"A table change needs the owner's sign-off. Once approved, regenerate with {UpdateVariable}=1 and commit the .sql diff with the migration.");
    }

    private static string Dump(string path)
    {
        using var connection = new SqliteConnection(new SqliteConnectionStringBuilder
        {
            DataSource = path, Mode = SqliteOpenMode.ReadOnly, Pooling = false
        }.ToString());
        connection.Open();
        using var command = connection.CreateCommand();
        command.CommandText = "SELECT type, name, sql FROM sqlite_schema WHERE sql IS NOT NULL ORDER BY type, name;";
        var builder = new StringBuilder(Header);
        using var reader = command.ExecuteReader();
        while (reader.Read())
        {
            builder.Append("-- ").Append(reader.GetString(0)).Append(' ').Append(reader.GetString(1)).Append('\n');
            builder.Append(Regex.Replace(reader.GetString(2), @"\s+", " ").Trim()).Append(";\n\n");
        }
        return builder.ToString();
    }

    /// <summary>
    /// Found from this source file, not from the build output: test binaries may be built with
    /// --artifacts-path outside the repository (a live vb.exe often holds VibeRails/bin).
    /// </summary>
    private static string RepositoryRoot([System.Runtime.CompilerServices.CallerFilePath] string sourceFile = "")
    {
        var directory = new DirectoryInfo(Path.GetDirectoryName(sourceFile) ?? AppContext.BaseDirectory);
        while (directory is not null)
        {
            if (File.Exists(Path.Combine(directory.FullName, "VibeRails.slnx")))
                return directory.FullName;
            directory = directory.Parent;
        }
        throw new InvalidOperationException("VibeRails.slnx was not found above " + sourceFile);
    }
}
