-- Generated by Tests/DB/SchemaSnapshotTests.cs from an empty database. Do not edit by hand.
-- Regenerate: set VIBE_RAILS_UPDATE_SCHEMA_SNAPSHOT=1, then: dotnet test Tests --filter SchemaSnapshotTests
-- Review schema changes under AGENTS.md: compatible additions are automatic; breaking changes require owner authorization.

-- index IX_BoardAdditionalCardSessions_Card
CREATE INDEX IX_BoardAdditionalCardSessions_Card ON BoardAdditionalCardSessions(CardId);

-- index IX_BoardAttachments_Card
CREATE INDEX IX_BoardAttachments_Card ON BoardAttachments(CardId);

-- index IX_BoardAttentionRequests_Card
CREATE INDEX IX_BoardAttentionRequests_Card ON BoardAttentionRequests(CardId, ResolvedUTC);

-- index IX_BoardAttentionRequests_Session
CREATE INDEX IX_BoardAttentionRequests_Session ON BoardAttentionRequests(SessionId, ResolvedUTC);

-- index IX_BoardCardLinks_LinkedCard
CREATE INDEX IX_BoardCardLinks_LinkedCard ON BoardCardLinks(LinkedCardId);

-- index IX_BoardCardSessions_Card
CREATE INDEX IX_BoardCardSessions_Card ON BoardCardSessions(CardId);

-- index IX_BoardCards_Column
CREATE INDEX IX_BoardCards_Column ON BoardCards(ColumnId, Position);

-- index IX_BoardChecks_Card
CREATE INDEX IX_BoardChecks_Card ON BoardChecks(CardId, StartedUTC DESC);

-- index IX_BoardColumns_Board
CREATE INDEX IX_BoardColumns_Board ON BoardColumns(BoardId, Position);

-- index IX_BoardColumns_Project
CREATE INDEX IX_BoardColumns_Project ON BoardColumns(ProjectPath, Position);

-- index IX_BoardComments_Card
CREATE INDEX IX_BoardComments_Card ON BoardComments(CardId, CreatedUTC);

-- index IX_BoardComments_RemoteSeq
CREATE INDEX IX_BoardComments_RemoteSeq ON BoardComments(RemoteSeq) WHERE RemoteSeq > 0;

-- index IX_BoardComments_TransferRemoteSeq
CREATE INDEX IX_BoardComments_TransferRemoteSeq ON BoardComments(TransferRemoteSeq) WHERE SyncBoardId IS NOT NULL;

-- index IX_BoardComments_Unsent
CREATE INDEX IX_BoardComments_Unsent ON BoardComments(CardId) WHERE RemoteSeq IS NULL;

-- index IX_BoardContextSamples_Card
CREATE INDEX IX_BoardContextSamples_Card ON BoardContextSamples(CardId, MeasuredUTC);

-- index IX_BoardHandoffs_Card
CREATE INDEX IX_BoardHandoffs_Card ON BoardHandoffs(CardId, CreatedUTC DESC, Id DESC);

-- index IX_BoardHistory_BoardTime
CREATE INDEX IX_BoardHistory_BoardTime ON BoardHistory(BoardId, CreatedUTC);

-- index IX_BoardJiraDeliveries_Card
CREATE INDEX IX_BoardJiraDeliveries_Card ON BoardJiraDeliveries(CardId, CreatedUTC);

-- index IX_BoardJiraDeliveries_Pending
CREATE INDEX IX_BoardJiraDeliveries_Pending ON BoardJiraDeliveries(Status, CreatedUTC);

-- index IX_BoardJiraLinks_Card
CREATE INDEX IX_BoardJiraLinks_Card ON BoardJiraLinks(CardId);

-- index IX_BoardLaneAutomationDispatch_Card
CREATE INDEX IX_BoardLaneAutomationDispatch_Card ON BoardLaneAutomationDispatch(CardId, DueUnixMs DESC);

-- index IX_BoardLaneStepReports_Event
CREATE INDEX IX_BoardLaneStepReports_Event ON BoardLaneStepReports(EventKey, JobId, Id DESC);

-- index IX_BoardLaneWorkflowSteps_Event
CREATE UNIQUE INDEX IX_BoardLaneWorkflowSteps_Event ON BoardLaneWorkflowSteps(EventKey, JobId);

-- index IX_BoardLaneWorkflows_Column
CREATE INDEX IX_BoardLaneWorkflows_Column ON BoardLaneWorkflows(ColumnId, Current);

-- index IX_BoardLaneWorkflows_Current
CREATE UNIQUE INDEX IX_BoardLaneWorkflows_Current ON BoardLaneWorkflows(CardId) WHERE Current = 1;

-- index IX_BoardPendingAdditionalAutomations_Due
CREATE INDEX IX_BoardPendingAdditionalAutomations_Due ON BoardPendingAdditionalAutomations(DueUnixMs);

-- index IX_BoardPendingAutomations_Due
CREATE INDEX IX_BoardPendingAutomations_Due ON BoardPendingAutomations(DueUnixMs);

-- index IX_BoardProjectKeys_Prefix
CREATE INDEX IX_BoardProjectKeys_Prefix ON BoardProjectKeys(Prefix);

-- index IX_BoardReviews_Card
CREATE INDEX IX_BoardReviews_Card ON BoardReviews(CardId, CreatedUTC DESC);

-- index IX_BoardReviews_Session
CREATE INDEX IX_BoardReviews_Session ON BoardReviews(json_extract(RecordJson, '$.sessionId'));

-- index IX_Boards_Project
CREATE INDEX IX_Boards_Project ON Boards(ProjectPath, Position);

-- index UX_BoardCards_CardKey
CREATE UNIQUE INDEX UX_BoardCards_CardKey ON BoardCards(CardKey) WHERE CardKey IS NOT NULL;

-- index UX_BoardCards_DisplayId
CREATE UNIQUE INDEX UX_BoardCards_DisplayId ON BoardCards(ProjectPath, DisplayId COLLATE NOCASE) WHERE DisplayId IS NOT NULL;

-- table BoardAdditionalCardSessions
CREATE TABLE BoardAdditionalCardSessions ( SessionId TEXT NOT NULL, CardId TEXT NOT NULL REFERENCES BoardCards(Id) ON DELETE CASCADE, TabId TEXT NULL, Selection TEXT NOT NULL, Cli TEXT NOT NULL, DisplayName TEXT NOT NULL, Origin TEXT NOT NULL, CreatedUTC TEXT NOT NULL, PRIMARY KEY (SessionId, CardId) );

-- table BoardAgentCompletions
CREATE TABLE BoardAgentCompletions ( ProjectPath TEXT NOT NULL, SessionId TEXT NOT NULL, Outcome TEXT NOT NULL, Summary TEXT NOT NULL, CompletedUTC TEXT NOT NULL, PRIMARY KEY (SessionId) );

-- table BoardAttachmentContents
CREATE TABLE BoardAttachmentContents ( AttachmentId TEXT PRIMARY KEY REFERENCES BoardAttachments(Id) ON DELETE CASCADE, Content BLOB NOT NULL );

-- table BoardAttachments
CREATE TABLE BoardAttachments ( Id TEXT PRIMARY KEY, CardId TEXT NOT NULL REFERENCES BoardCards(Id) ON DELETE CASCADE, Name TEXT NOT NULL, MimeType TEXT NOT NULL, Bytes INTEGER NOT NULL, DataUrl TEXT NOT NULL, CreatedUTC TEXT NOT NULL );

-- table BoardAttentionRequests
CREATE TABLE BoardAttentionRequests ( CommentId TEXT PRIMARY KEY REFERENCES BoardComments(Id) ON DELETE CASCADE, CardId TEXT NOT NULL REFERENCES BoardCards(Id) ON DELETE CASCADE, SessionId TEXT, ResolvedUTC TEXT );

-- table BoardCardLinks
CREATE TABLE BoardCardLinks ( CardId TEXT NOT NULL REFERENCES BoardCards(Id) ON DELETE CASCADE, LinkedCardId TEXT NOT NULL REFERENCES BoardCards(Id) ON DELETE CASCADE, PRIMARY KEY (CardId, LinkedCardId), CHECK (CardId < LinkedCardId) );

-- table BoardCardOptions
CREATE TABLE BoardCardOptions ( CardId TEXT PRIMARY KEY REFERENCES BoardCards(Id) ON DELETE CASCADE, OptionsJson TEXT NOT NULL );

-- table BoardCardSequences
CREATE TABLE BoardCardSequences ( ProjectPath TEXT PRIMARY KEY COLLATE NOCASE, LastNumber INTEGER NOT NULL );

-- table BoardCardSessions
CREATE TABLE BoardCardSessions ( SessionId TEXT PRIMARY KEY, CardId TEXT NOT NULL REFERENCES BoardCards(Id) ON DELETE CASCADE, TabId TEXT NULL, Selection TEXT NOT NULL, Cli TEXT NOT NULL, DisplayName TEXT NOT NULL, Origin TEXT NOT NULL, CreatedUTC TEXT NOT NULL );

-- table BoardCards
CREATE TABLE BoardCards ( Id TEXT PRIMARY KEY, ProjectPath TEXT NOT NULL, Number INTEGER NOT NULL, ColumnId TEXT NOT NULL REFERENCES BoardColumns(Id), Position INTEGER NOT NULL, Title TEXT NOT NULL, Description TEXT NOT NULL DEFAULT '', Assignee TEXT NULL, Priority TEXT NOT NULL DEFAULT 'medium', Type TEXT NOT NULL DEFAULT 'task', Points INTEGER NULL, Tags TEXT NOT NULL DEFAULT '[]', Blocked INTEGER NOT NULL DEFAULT 0, CreatedUTC TEXT NOT NULL, UpdatedUTC TEXT NOT NULL, Flagged INTEGER NOT NULL DEFAULT 0, CardKey TEXT, DeletedUTC TEXT, DisplayId TEXT, AgentMade INTEGER NOT NULL DEFAULT 0, AgentMadeBy TEXT, AgentMadeSessionId TEXT, UNIQUE(ProjectPath, Number) );

-- table BoardChecks
CREATE TABLE BoardChecks ( Id TEXT PRIMARY KEY, CardId TEXT NOT NULL REFERENCES BoardCards(Id) ON DELETE CASCADE, RunId TEXT NOT NULL, ActionId TEXT NOT NULL, StartedUTC TEXT NOT NULL, EndedUTC TEXT NULL, SummaryJson TEXT NOT NULL, ResultJson TEXT NULL, UNIQUE(CardId, RunId, ActionId) );

-- table BoardColumns
CREATE TABLE BoardColumns ( Id TEXT PRIMARY KEY, ProjectPath TEXT NOT NULL, Name TEXT NOT NULL, Position INTEGER NOT NULL, Color TEXT NOT NULL, CreatedUTC TEXT NOT NULL, UpdatedUTC TEXT NOT NULL, BoardId TEXT NULL );

-- table BoardComments
CREATE TABLE BoardComments ( Id TEXT PRIMARY KEY, CardId TEXT NOT NULL REFERENCES BoardCards(Id) ON DELETE CASCADE, AuthorKind TEXT NOT NULL, AuthorLabel TEXT NOT NULL, AuthorCli TEXT NULL, SessionId TEXT NULL, Body TEXT NOT NULL, CreatedUTC TEXT NOT NULL, Kind TEXT NOT NULL DEFAULT 'comment' , Changes TEXT, RemoteSeq INTEGER, SyncBoardId TEXT, DiscussionHidden INTEGER NOT NULL DEFAULT 0, TransferRemoteSeq INTEGER);

-- table BoardCommitSnapshots
CREATE TABLE BoardCommitSnapshots ( CardId TEXT NOT NULL, Sha TEXT NOT NULL, SnapshotJson TEXT NOT NULL, PRIMARY KEY (CardId, Sha), FOREIGN KEY (CardId, Sha) REFERENCES BoardCommits(CardId, Sha) ON DELETE CASCADE );

-- table BoardCommits
CREATE TABLE BoardCommits ( CardId TEXT NOT NULL REFERENCES BoardCards(Id) ON DELETE CASCADE, Sha TEXT NOT NULL, Author TEXT NOT NULL, Message TEXT NOT NULL, CommittedUTC TEXT NOT NULL, LinkedUTC TEXT NOT NULL, PRIMARY KEY (CardId, Sha) );

-- table BoardContextSamples
CREATE TABLE BoardContextSamples ( Id TEXT PRIMARY KEY, CardId TEXT NOT NULL REFERENCES BoardCards(Id) ON DELETE CASCADE, SessionId TEXT NULL, MeasuredUTC TEXT NOT NULL, Intent TEXT NOT NULL, Cli TEXT NULL, Selection TEXT NULL, Tokens INTEGER NOT NULL, Chars INTEGER NOT NULL, PromptTokens INTEGER NOT NULL, CardReadTokens INTEGER NOT NULL, Breakdown TEXT NOT NULL );

-- table BoardContextSettings
CREATE TABLE BoardContextSettings ( BoardId TEXT PRIMARY KEY REFERENCES Boards(Id) ON DELETE CASCADE, ContextJson TEXT NOT NULL, Revision INTEGER NOT NULL );

-- table BoardDeletedComments
CREATE TABLE BoardDeletedComments ( CommentId TEXT PRIMARY KEY REFERENCES BoardComments(Id) ON DELETE CASCADE, DeletedUTC TEXT NOT NULL );

-- table BoardDisplaySequences
CREATE TABLE BoardDisplaySequences ( ProjectPath TEXT NOT NULL COLLATE NOCASE, Prefix TEXT NOT NULL COLLATE NOCASE, LastNumber INTEGER NOT NULL, PRIMARY KEY (ProjectPath, Prefix) );

-- table BoardHandoffs
CREATE TABLE BoardHandoffs ( Id TEXT PRIMARY KEY, CardId TEXT NOT NULL REFERENCES BoardCards(Id) ON DELETE CASCADE, Json TEXT NOT NULL, CreatedUTC TEXT NOT NULL);

-- table BoardHistory
CREATE TABLE BoardHistory ( Id TEXT PRIMARY KEY, BoardId TEXT NOT NULL, ProjectPath TEXT NOT NULL, Kind TEXT NOT NULL, Body TEXT NOT NULL, CreatedUTC TEXT NOT NULL );

-- table BoardJiraConnections
CREATE TABLE BoardJiraConnections ( Id TEXT PRIMARY KEY, ProjectPath TEXT NOT NULL, BoardId TEXT NOT NULL, SiteUrl TEXT NOT NULL, Email TEXT NOT NULL DEFAULT '', HasToken INTEGER NOT NULL DEFAULT 0, AuthStatus TEXT NOT NULL DEFAULT 'none', StoryPointsFieldId TEXT NULL, Jql TEXT NOT NULL DEFAULT '', Enabled INTEGER NOT NULL DEFAULT 0, DisabledReason TEXT NULL, OverflowColumnId TEXT NULL, LastTestedUTC TEXT NULL, LastPullUTC TEXT NULL, LastReport TEXT NULL, BoardLink TEXT, JiraBoardId TEXT, JiraBoardName TEXT, ColumnMap TEXT, NarrowJql TEXT, SkipOldDone INTEGER, DedicatedBoard INTEGER, UNIQUE(ProjectPath, BoardId) );

-- table BoardJiraDeliveries
CREATE TABLE BoardJiraDeliveries ( Id TEXT PRIMARY KEY, CardId TEXT NOT NULL REFERENCES BoardCards(Id) ON DELETE CASCADE, ConnectionId TEXT NOT NULL, IssueId TEXT NOT NULL, Kind TEXT NOT NULL, SourceId TEXT NOT NULL, Body TEXT NOT NULL, Status TEXT NOT NULL DEFAULT 'pending', Message TEXT, Url TEXT, CreatedUTC TEXT NOT NULL, UpdatedUTC TEXT NOT NULL, UNIQUE(ConnectionId, IssueId, Kind, SourceId) );

-- table BoardJiraLinks
CREATE TABLE BoardJiraLinks ( CardId TEXT NOT NULL REFERENCES BoardCards(Id) ON DELETE CASCADE, SiteId TEXT NOT NULL, IssueId TEXT NOT NULL, IssueKey TEXT NOT NULL, AssigneeDisplay TEXT NULL, IssueUpdated TEXT NOT NULL, LastPulledUTC TEXT NOT NULL, Mapping TEXT, UNIQUE(SiteId, IssueId) );

-- table BoardLaneAdditionalAutomations
CREATE TABLE BoardLaneAdditionalAutomations ( ColumnId TEXT NOT NULL REFERENCES BoardLaneAutomations(ColumnId) ON DELETE CASCADE, JobId INTEGER NOT NULL, Position INTEGER NOT NULL, PRIMARY KEY (ColumnId, JobId) );

-- table BoardLaneAutomationDispatch
CREATE TABLE BoardLaneAutomationDispatch ( EventKey TEXT NOT NULL, JobId INTEGER NOT NULL, CardId TEXT NOT NULL, ColumnId TEXT NOT NULL, DueUnixMs INTEGER NOT NULL, Status TEXT NOT NULL, Reason TEXT NOT NULL, RunId TEXT NULL, LastAttemptUnixMs INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (EventKey, JobId) );

-- table BoardLaneAutomations
CREATE TABLE BoardLaneAutomations ( ColumnId TEXT PRIMARY KEY REFERENCES BoardColumns(Id) ON DELETE CASCADE, JobId INTEGER NULL, Revision INTEGER NOT NULL );

-- table BoardLaneStepReports
CREATE TABLE BoardLaneStepReports ( Id INTEGER PRIMARY KEY AUTOINCREMENT, EventKey TEXT NOT NULL, JobId INTEGER NOT NULL, Status TEXT NOT NULL, Summary TEXT NOT NULL, RunId TEXT NULL, ReviewId TEXT NULL, SessionId TEXT NULL, CreatedUTC TEXT NOT NULL );

-- table BoardLaneWorkflowSteps
CREATE TABLE BoardLaneWorkflowSteps ( WorkflowId TEXT NOT NULL REFERENCES BoardLaneWorkflows(Id), JobId INTEGER NOT NULL, Position INTEGER NOT NULL, EventKey TEXT NULL, PRIMARY KEY (WorkflowId, JobId) );

-- table BoardLaneWorkflows
CREATE TABLE BoardLaneWorkflows ( Id TEXT PRIMARY KEY, CardId TEXT NOT NULL, ColumnId TEXT NOT NULL, CreatedUnixMs INTEGER NOT NULL, Current INTEGER NOT NULL DEFAULT 1 );

-- table BoardPendingAdditionalAutomations
CREATE TABLE BoardPendingAdditionalAutomations ( CardId TEXT NOT NULL REFERENCES BoardCards(Id) ON DELETE CASCADE, ColumnId TEXT NOT NULL, JobId INTEGER NOT NULL, EventKey TEXT NOT NULL, DueUnixMs INTEGER NOT NULL, PRIMARY KEY (CardId, JobId), FOREIGN KEY (ColumnId, JobId) REFERENCES BoardLaneAdditionalAutomations(ColumnId, JobId) ON DELETE CASCADE );

-- table BoardPendingAutomations
CREATE TABLE BoardPendingAutomations ( CardId TEXT PRIMARY KEY REFERENCES BoardCards(Id) ON DELETE CASCADE, ColumnId TEXT NOT NULL REFERENCES BoardColumns(Id) ON DELETE CASCADE, JobId INTEGER NOT NULL, EventKey TEXT NOT NULL, DueUnixMs INTEGER NOT NULL );

-- table BoardProjectKeys
CREATE TABLE BoardProjectKeys ( ProjectPath TEXT PRIMARY KEY COLLATE NOCASE, Prefix TEXT NOT NULL, CreatedUTC TEXT NOT NULL );

-- table BoardRecallEmbeddings
CREATE TABLE BoardRecallEmbeddings ( CardId TEXT PRIMARY KEY REFERENCES BoardCards(Id) ON DELETE CASCADE, Version TEXT NOT NULL, Embedding TEXT NOT NULL);

-- table BoardReviewSettings
CREATE TABLE BoardReviewSettings ( CardId TEXT PRIMARY KEY REFERENCES BoardCards(Id) ON DELETE CASCADE, SettingsJson TEXT NOT NULL );

-- table BoardReviews
CREATE TABLE BoardReviews ( Id TEXT PRIMARY KEY, CardId TEXT NOT NULL REFERENCES BoardCards(Id) ON DELETE CASCADE, CreatedUTC TEXT NOT NULL, ReportedUTC TEXT, RecordJson TEXT NOT NULL );

-- table BoardSearchEmbeddings
CREATE TABLE BoardSearchEmbeddings ( CardId TEXT NOT NULL REFERENCES BoardCards(Id) ON DELETE CASCADE, PassageId TEXT NOT NULL, Version TEXT NOT NULL, Embedding TEXT NOT NULL, PRIMARY KEY(CardId, PassageId));

-- table BoardSharedOrigins
CREATE TABLE BoardSharedOrigins ( BoardId TEXT PRIMARY KEY REFERENCES Boards(Id) ON DELETE CASCADE, RemoteBoardId TEXT NOT NULL UNIQUE, DestinationKey TEXT NOT NULL, KeyPrefix TEXT NOT NULL );

-- table BoardStarterWorkflows
CREATE TABLE BoardStarterWorkflows ( ColumnId TEXT PRIMARY KEY REFERENCES BoardColumns(Id) ON DELETE CASCADE, RecipeId TEXT NOT NULL, Completed INTEGER NOT NULL DEFAULT 0 );

-- table BoardSyncLinks
CREATE TABLE BoardSyncLinks ( BoardId TEXT PRIMARY KEY REFERENCES Boards(Id) ON DELETE CASCADE, RemoteBoardId TEXT NOT NULL, Cursor INTEGER NOT NULL DEFAULT 0, Enabled INTEGER NOT NULL DEFAULT 1, LayoutHash TEXT, LastSyncUTC TEXT, LastError TEXT, CreatedUTC TEXT NOT NULL, UpdatedUTC TEXT NOT NULL , DestinationKey TEXT, ActivitySchema INTEGER NOT NULL DEFAULT 0, ActivityAfter TEXT);

-- table BoardSyncRejectedFields
CREATE TABLE BoardSyncRejectedFields ( EntryId TEXT NOT NULL REFERENCES BoardComments(Id) ON DELETE CASCADE, Field TEXT NOT NULL, PRIMARY KEY (EntryId, Field) );

-- table BoardSyncSkippedEntries
CREATE TABLE BoardSyncSkippedEntries ( BoardId TEXT NOT NULL REFERENCES Boards(Id) ON DELETE CASCADE, EntryId TEXT NOT NULL, Seq INTEGER NOT NULL, CardKey TEXT NOT NULL, Kind TEXT NOT NULL, Reason TEXT NOT NULL, SkippedUTC TEXT NOT NULL, Version TEXT, PRIMARY KEY (BoardId, EntryId) );

-- table Boards
CREATE TABLE Boards ( Id TEXT PRIMARY KEY, ProjectPath TEXT NOT NULL, Name TEXT NOT NULL, Position INTEGER NOT NULL, CreatedUTC TEXT NOT NULL, UpdatedUTC TEXT NOT NULL , DisplayPrefix TEXT, SyncEnabled INTEGER NOT NULL DEFAULT 1);

-- table SchemaMigrations
CREATE TABLE SchemaMigrations ( Component TEXT NOT NULL, Version INTEGER NOT NULL CHECK (Version > 0), AppliedUTC TEXT NOT NULL, AppliedBy TEXT, PRIMARY KEY (Component, Version) );

-- table sqlite_sequence
CREATE TABLE sqlite_sequence(name,seq);

-- trigger BoardCards_AdditionalLaneAutomation_Insert
CREATE TRIGGER BoardCards_AdditionalLaneAutomation_Insert AFTER INSERT ON BoardCards BEGIN INSERT INTO BoardPendingAdditionalAutomations (CardId, ColumnId, JobId, EventKey, DueUnixMs) SELECT NEW.Id, NEW.ColumnId, a.JobId, lower(hex(randomblob(16))), CAST(unixepoch('subsec') * 1000 AS INTEGER) + 60000 FROM BoardLaneAdditionalAutomations a WHERE a.ColumnId = NEW.ColumnId; END;

-- trigger BoardCards_AdditionalLaneAutomation_Move
CREATE TRIGGER BoardCards_AdditionalLaneAutomation_Move AFTER UPDATE OF ColumnId ON BoardCards WHEN OLD.ColumnId <> NEW.ColumnId BEGIN DELETE FROM BoardPendingAdditionalAutomations WHERE CardId = NEW.Id; INSERT INTO BoardPendingAdditionalAutomations (CardId, ColumnId, JobId, EventKey, DueUnixMs) SELECT NEW.Id, NEW.ColumnId, a.JobId, lower(hex(randomblob(16))), CAST(unixepoch('subsec') * 1000 AS INTEGER) + 60000 FROM BoardLaneAdditionalAutomations a WHERE a.ColumnId = NEW.ColumnId; END;

-- trigger BoardCards_LaneAutomation_Insert
CREATE TRIGGER BoardCards_LaneAutomation_Insert AFTER INSERT ON BoardCards BEGIN INSERT INTO BoardPendingAutomations (CardId, ColumnId, JobId, EventKey, DueUnixMs) SELECT NEW.Id, NEW.ColumnId, a.JobId, lower(hex(randomblob(16))), CAST(unixepoch('subsec') * 1000 AS INTEGER) + 60000 FROM BoardLaneAutomations a WHERE a.ColumnId = NEW.ColumnId AND a.JobId IS NOT NULL; END;

-- trigger BoardCards_LaneAutomation_Move
CREATE TRIGGER BoardCards_LaneAutomation_Move AFTER UPDATE OF ColumnId ON BoardCards WHEN OLD.ColumnId <> NEW.ColumnId BEGIN DELETE FROM BoardPendingAutomations WHERE CardId = NEW.Id; INSERT INTO BoardPendingAutomations (CardId, ColumnId, JobId, EventKey, DueUnixMs) SELECT NEW.Id, NEW.ColumnId, a.JobId, lower(hex(randomblob(16))), CAST(unixepoch('subsec') * 1000 AS INTEGER) + 60000 FROM BoardLaneAutomations a WHERE a.ColumnId = NEW.ColumnId AND a.JobId IS NOT NULL; END;

-- trigger BoardCards_ResolveAttention
CREATE TRIGGER BoardCards_ResolveAttention AFTER UPDATE OF Flagged ON BoardCards WHEN NEW.Flagged = 0 BEGIN UPDATE BoardAttentionRequests SET ResolvedUTC = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE CardId = NEW.Id AND ResolvedUTC IS NULL; END;

-- trigger BoardCards_Workflow_Insert
CREATE TRIGGER BoardCards_Workflow_Insert BEFORE INSERT ON BoardCards BEGIN UPDATE BoardLaneWorkflows SET Current = 0 WHERE CardId = NEW.Id AND Current = 1; INSERT INTO BoardLaneWorkflows (Id, CardId, ColumnId, CreatedUnixMs) SELECT lower(hex(randomblob(16))), NEW.Id, NEW.ColumnId, CAST(unixepoch('subsec') * 1000 AS INTEGER) WHERE EXISTS (SELECT 1 FROM BoardLaneAutomations WHERE ColumnId = NEW.ColumnId AND JobId IS NOT NULL); INSERT INTO BoardLaneWorkflowSteps (WorkflowId, JobId, Position) SELECT w.Id, a.JobId, 0 FROM BoardLaneWorkflows w JOIN BoardLaneAutomations a ON a.ColumnId = w.ColumnId WHERE w.CardId = NEW.Id AND w.Current = 1 AND a.JobId IS NOT NULL UNION ALL SELECT w.Id, a.JobId, a.Position FROM BoardLaneWorkflows w JOIN BoardLaneAdditionalAutomations a ON a.ColumnId = w.ColumnId WHERE w.CardId = NEW.Id AND w.Current = 1; END;

-- trigger BoardCards_Workflow_Move
CREATE TRIGGER BoardCards_Workflow_Move BEFORE UPDATE OF ColumnId ON BoardCards WHEN OLD.ColumnId <> NEW.ColumnId BEGIN UPDATE BoardLaneWorkflows SET Current = 0 WHERE CardId = NEW.Id AND Current = 1; INSERT INTO BoardLaneWorkflows (Id, CardId, ColumnId, CreatedUnixMs) SELECT lower(hex(randomblob(16))), NEW.Id, NEW.ColumnId, CAST(unixepoch('subsec') * 1000 AS INTEGER) WHERE EXISTS (SELECT 1 FROM BoardLaneAutomations WHERE ColumnId = NEW.ColumnId AND JobId IS NOT NULL); INSERT INTO BoardLaneWorkflowSteps (WorkflowId, JobId, Position) SELECT w.Id, a.JobId, 0 FROM BoardLaneWorkflows w JOIN BoardLaneAutomations a ON a.ColumnId = w.ColumnId WHERE w.CardId = NEW.Id AND w.Current = 1 AND a.JobId IS NOT NULL UNION ALL SELECT w.Id, a.JobId, a.Position FROM BoardLaneWorkflows w JOIN BoardLaneAdditionalAutomations a ON a.ColumnId = w.ColumnId WHERE w.CardId = NEW.Id AND w.Current = 1; END;

-- trigger BoardColumns_HistoryChanged
CREATE TRIGGER BoardColumns_HistoryChanged AFTER UPDATE OF Name, Color, Position ON BoardColumns WHEN OLD.Name IS NOT NEW.Name OR OLD.Color IS NOT NEW.Color OR OLD.Position IS NOT NEW.Position BEGIN INSERT INTO BoardHistory VALUES ('bh_' || lower(hex(randomblob(16))), COALESCE(NEW.BoardId, ''), NEW.ProjectPath, 'change', 'Lane ' || OLD.Name || ': ' || CASE WHEN OLD.Name IS NOT NEW.Name THEN 'name → ' || NEW.Name || '; ' ELSE '' END || CASE WHEN OLD.Color IS NOT NEW.Color THEN 'colour → ' || NEW.Color || '; ' ELSE '' END || CASE WHEN OLD.Position IS NOT NEW.Position THEN 'position → ' || NEW.Position ELSE '' END, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')); END;

-- trigger BoardColumns_HistoryCreated
CREATE TRIGGER BoardColumns_HistoryCreated AFTER INSERT ON BoardColumns BEGIN INSERT INTO BoardHistory VALUES ('bh_' || lower(hex(randomblob(16))), COALESCE(NEW.BoardId, ''), NEW.ProjectPath, 'created', 'Created lane: ' || NEW.Name, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')); END;

-- trigger BoardColumns_HistoryDeleted
CREATE TRIGGER BoardColumns_HistoryDeleted AFTER DELETE ON BoardColumns BEGIN INSERT INTO BoardHistory VALUES ('bh_' || lower(hex(randomblob(16))), COALESCE(OLD.BoardId, ''), OLD.ProjectPath, 'deleted', 'Deleted lane: ' || OLD.Name, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')); END;

-- trigger BoardComments_QueueJira
CREATE TRIGGER BoardComments_QueueJira AFTER INSERT ON BoardComments WHEN NEW.Kind IN ('comment', 'note') AND NEW.RemoteSeq IS NULL AND NEW.SyncBoardId IS NULL AND NOT (NEW.AuthorKind = 'agent' AND NEW.AuthorLabel = 'Jira' AND NEW.AuthorCli IS NULL AND NEW.SessionId IS NULL) AND COALESCE(NEW.DiscussionHidden, 0) = 0 AND CASE WHEN json_valid(NEW.Changes) THEN COALESCE(json_extract(NEW.Changes, '$.jiraCopy'), 0) ELSE 0 END = 0 AND CASE WHEN json_valid(NEW.Changes) THEN COALESCE(json_extract(NEW.Changes, '$.syncToJira.to'), 1) ELSE 1 END != 0 BEGIN INSERT OR IGNORE INTO BoardJiraDeliveries (Id, CardId, ConnectionId, IssueId, Kind, SourceId, Body, CreatedUTC, UpdatedUTC) SELECT lower(hex(randomblob(16))), c.Id, j.SiteId, j.IssueId, 'comment', NEW.Id, NEW.AuthorLabel || ': ' || NEW.Body, NEW.CreatedUTC, NEW.CreatedUTC FROM BoardCards c JOIN BoardJiraLinks j ON j.CardId = c.Id JOIN BoardJiraConnections conn ON conn.Id = j.SiteId AND conn.ProjectPath = c.ProjectPath WHERE c.Id = NEW.CardId AND c.DeletedUTC IS NULL; END;

-- trigger BoardLaneAutomations_ClearAdditional
CREATE TRIGGER BoardLaneAutomations_ClearAdditional AFTER UPDATE ON BoardLaneAutomations BEGIN DELETE FROM BoardLaneAdditionalAutomations WHERE ColumnId = NEW.ColumnId; END;

-- trigger BoardPendingAdditionalAutomations_RecordCancellation
CREATE TRIGGER BoardPendingAdditionalAutomations_RecordCancellation BEFORE DELETE ON BoardPendingAdditionalAutomations BEGIN INSERT INTO BoardLaneAutomationDispatch (EventKey, JobId, CardId, ColumnId, DueUnixMs, Status, Reason) VALUES (OLD.EventKey, OLD.JobId, OLD.CardId, OLD.ColumnId, OLD.DueUnixMs, 'Cancelled', CASE WHEN NOT EXISTS (SELECT 1 FROM BoardCards WHERE Id = OLD.CardId AND DeletedUTC IS NULL) THEN 'Card was deleted.' WHEN NOT EXISTS (SELECT 1 FROM BoardCards WHERE Id = OLD.CardId AND ColumnId = OLD.ColumnId) THEN 'Card left the destination lane; a later entry starts a new settling period.' ELSE 'Lane Automation assignment changed or the pending entry was removed.' END) ON CONFLICT(EventKey, JobId) DO UPDATE SET Status = excluded.Status, Reason = excluded.Reason WHERE BoardLaneAutomationDispatch.Status = 'Waiting'; END;

-- trigger BoardPendingAdditionalAutomations_Workflow
CREATE TRIGGER BoardPendingAdditionalAutomations_Workflow AFTER INSERT ON BoardPendingAdditionalAutomations BEGIN UPDATE BoardLaneWorkflowSteps SET EventKey = NEW.EventKey WHERE JobId = NEW.JobId AND WorkflowId IN ( SELECT Id FROM BoardLaneWorkflows WHERE CardId = NEW.CardId AND ColumnId = NEW.ColumnId AND Current = 1); END;

-- trigger BoardPendingAutomations_RecordCancellation
CREATE TRIGGER BoardPendingAutomations_RecordCancellation BEFORE DELETE ON BoardPendingAutomations BEGIN INSERT INTO BoardLaneAutomationDispatch (EventKey, JobId, CardId, ColumnId, DueUnixMs, Status, Reason) VALUES (OLD.EventKey, OLD.JobId, OLD.CardId, OLD.ColumnId, OLD.DueUnixMs, 'Cancelled', CASE WHEN NOT EXISTS (SELECT 1 FROM BoardCards WHERE Id = OLD.CardId AND DeletedUTC IS NULL) THEN 'Card was deleted.' WHEN NOT EXISTS (SELECT 1 FROM BoardCards WHERE Id = OLD.CardId AND ColumnId = OLD.ColumnId) THEN 'Card left the destination lane; a later entry starts a new settling period.' ELSE 'Lane Automation assignment changed or the pending entry was removed.' END) ON CONFLICT(EventKey, JobId) DO UPDATE SET Status = excluded.Status, Reason = excluded.Reason WHERE BoardLaneAutomationDispatch.Status = 'Waiting'; END;

-- trigger BoardPendingAutomations_Workflow
CREATE TRIGGER BoardPendingAutomations_Workflow AFTER INSERT ON BoardPendingAutomations BEGIN UPDATE BoardLaneWorkflowSteps SET EventKey = NEW.EventKey WHERE JobId = NEW.JobId AND WorkflowId IN ( SELECT Id FROM BoardLaneWorkflows WHERE CardId = NEW.CardId AND ColumnId = NEW.ColumnId AND Current = 1); END;

-- trigger BoardStarterWorkflows_SettingsInsert
CREATE TRIGGER BoardStarterWorkflows_SettingsInsert AFTER INSERT ON BoardLaneAutomations BEGIN UPDATE BoardStarterWorkflows SET Completed = 1 WHERE ColumnId = NEW.ColumnId; END;

-- trigger BoardStarterWorkflows_SettingsUpdate
CREATE TRIGGER BoardStarterWorkflows_SettingsUpdate AFTER UPDATE ON BoardLaneAutomations BEGIN UPDATE BoardStarterWorkflows SET Completed = 1 WHERE ColumnId = NEW.ColumnId; END;

-- trigger Boards_DeleteJiraConnection
CREATE TRIGGER Boards_DeleteJiraConnection AFTER DELETE ON Boards BEGIN DELETE FROM BoardJiraConnections WHERE BoardId = OLD.Id; END;

-- trigger Boards_HistoryCreated
CREATE TRIGGER Boards_HistoryCreated AFTER INSERT ON Boards BEGIN INSERT INTO BoardHistory VALUES ('bh_' || lower(hex(randomblob(16))), NEW.Id, NEW.ProjectPath, 'created', 'Created board: ' || NEW.Name, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')); END;

-- trigger Boards_HistoryName
CREATE TRIGGER Boards_HistoryName AFTER UPDATE OF Name ON Boards WHEN OLD.Name IS NOT NEW.Name BEGIN INSERT INTO BoardHistory VALUES ('bh_' || lower(hex(randomblob(16))), NEW.Id, NEW.ProjectPath, 'change', 'Board name: ' || OLD.Name || ' → ' || NEW.Name, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')); END;

-- trigger TR_BoardComments_KeepTransferLocal
CREATE TRIGGER TR_BoardComments_KeepTransferLocal AFTER UPDATE OF RemoteSeq ON BoardComments WHEN NEW.SyncBoardId IS NOT NULL AND NEW.RemoteSeq IS NOT 0 BEGIN UPDATE BoardComments SET RemoteSeq = 0 WHERE Id = NEW.Id; END;

-- view BoardSyncLog
CREATE VIEW BoardSyncLog AS SELECT rowid, Id, CardId, AuthorKind, AuthorLabel, AuthorCli, SessionId, Body, CreatedUTC, Kind, Changes, SyncBoardId, DiscussionHidden, CASE WHEN SyncBoardId IS NULL THEN RemoteSeq ELSE TransferRemoteSeq END AS RemoteSeq FROM BoardComments;

