-- Generated by Tests/DB/SchemaSnapshotTests.cs from an empty database. Do not edit by hand.
-- Regenerate: set VIBE_RAILS_UPDATE_SCHEMA_SNAPSHOT=1, then: dotnet test Tests --filter SchemaSnapshotTests
-- Every diff in this file is a table change and needs the owner's sign-off (vibe-data/docs/db-migration-policy.md).

-- index IX_ProxyExchanges_CreatedUTC
CREATE INDEX IX_ProxyExchanges_CreatedUTC ON ProxyExchanges(CreatedUTC DESC);

-- index IX_ProxyExchanges_SessionId
CREATE INDEX IX_ProxyExchanges_SessionId ON ProxyExchanges(SessionId);

-- table ProxyExchanges
CREATE TABLE ProxyExchanges ( Id TEXT NOT NULL PRIMARY KEY, CreatedUTC TEXT NOT NULL, Provider TEXT NOT NULL, Method TEXT NOT NULL, Path TEXT NOT NULL, StatusCode INTEGER NOT NULL, RequestBefore TEXT NOT NULL, RequestAfter TEXT NOT NULL, ResponseBody TEXT NOT NULL, ResponseTruncated INTEGER NOT NULL, CharsBefore INTEGER NOT NULL, CharsAfter INTEGER NOT NULL, ResponseChars INTEGER NOT NULL, ElapsedMs INTEGER NOT NULL, SessionId TEXT NULL );

-- table SchemaMigrations
CREATE TABLE SchemaMigrations ( Component TEXT NOT NULL, Version INTEGER NOT NULL CHECK (Version > 0), AppliedUTC TEXT NOT NULL, AppliedBy TEXT, PRIMARY KEY (Component, Version) );

