-- Generated by Tests/DB/SchemaSnapshotTests.cs from an empty database. Do not edit by hand.
-- Regenerate: set VIBE_RAILS_UPDATE_SCHEMA_SNAPSHOT=1, then: dotnet test Tests --filter SchemaSnapshotTests
-- Review schema changes under AGENTS.md: compatible additions are automatic; breaking changes require owner authorization.

-- index IX_SearchChunks_Source
CREATE INDEX IX_SearchChunks_Source ON SearchChunks(SourceId,Position);

-- index IX_SearchChunks_Work
CREATE INDEX IX_SearchChunks_Work ON SearchChunks(ModelVersion,RetryAt,LeaseUntil);

-- index IX_SearchDocuments_Kind
CREATE INDEX IX_SearchDocuments_Kind ON SearchDocuments(Kind, Id);

-- index IX_SearchDocuments_Session
CREATE INDEX IX_SearchDocuments_Session ON SearchDocuments(SessionId);

-- index IX_SearchSources_Document
CREATE INDEX IX_SearchSources_Document ON SearchSources(DocumentId);

-- index IX_SearchSources_Work
CREATE INDEX IX_SearchSources_Work ON SearchSources(ChunkVersion, RetryAt, LeaseUntil);

-- table SchemaMigrations
CREATE TABLE SchemaMigrations ( Component TEXT NOT NULL, Version INTEGER NOT NULL CHECK (Version > 0), AppliedUTC TEXT NOT NULL, AppliedBy TEXT, PRIMARY KEY (Component, Version) );

-- table SearchCheckpoints
CREATE TABLE SearchCheckpoints ( Kind TEXT PRIMARY KEY, Cursor TEXT NOT NULL DEFAULT '', Epoch INTEGER NOT NULL DEFAULT 1, Lease TEXT, LeaseUntil INTEGER NOT NULL DEFAULT 0, CompletedUtc TEXT, Attempts INTEGER NOT NULL DEFAULT 0, RetryAt INTEGER NOT NULL DEFAULT 0, Error TEXT);

-- table SearchChunks
CREATE TABLE SearchChunks ( Id TEXT PRIMARY KEY, SourceId TEXT NOT NULL REFERENCES SearchSources(Id) ON DELETE CASCADE, Position INTEGER NOT NULL, Text TEXT NOT NULL, Hash TEXT NOT NULL, ModelVersion TEXT, Attempts INTEGER NOT NULL DEFAULT 0, RetryAt INTEGER NOT NULL DEFAULT 0, Lease TEXT, LeaseUntil INTEGER NOT NULL DEFAULT 0, Error TEXT);

-- table SearchDocuments
CREATE TABLE SearchDocuments ( Id TEXT PRIMARY KEY, Kind TEXT NOT NULL, ProjectPath TEXT NOT NULL, SessionId TEXT, Metadata TEXT NOT NULL, SeenEpoch INTEGER NOT NULL);

-- table SearchSources
CREATE TABLE SearchSources ( Id TEXT PRIMARY KEY, DocumentId TEXT NOT NULL REFERENCES SearchDocuments(Id) ON DELETE CASCADE, SourceKey TEXT NOT NULL, Text TEXT NOT NULL, Title TEXT NOT NULL, Hash TEXT NOT NULL, ChunkVersion TEXT, Attempts INTEGER NOT NULL DEFAULT 0, RetryAt INTEGER NOT NULL DEFAULT 0, Lease TEXT, LeaseUntil INTEGER NOT NULL DEFAULT 0, Error TEXT);

-- table SearchSources_fts
CREATE VIRTUAL TABLE SearchSources_fts USING fts5(Text, Title, content='SearchSources', content_rowid='rowid');

-- table SearchSources_fts_config
CREATE TABLE 'SearchSources_fts_config'(k PRIMARY KEY, v) WITHOUT ROWID;

-- table SearchSources_fts_data
CREATE TABLE 'SearchSources_fts_data'(id INTEGER PRIMARY KEY, block BLOB);

-- table SearchSources_fts_docsize
CREATE TABLE 'SearchSources_fts_docsize'(id INTEGER PRIMARY KEY, sz BLOB);

-- table SearchSources_fts_idx
CREATE TABLE 'SearchSources_fts_idx'(segid, term, pgno, PRIMARY KEY(segid, term)) WITHOUT ROWID;

-- table sqlite_sequence
CREATE TABLE sqlite_sequence(name,seq);

-- table vec_search_chunks
CREATE VIRTUAL TABLE vec_search_chunks USING vec0( Id TEXT PRIMARY KEY, Embedding FLOAT[384] distance_metric=cosine);

-- table vec_search_chunks_chunks
CREATE TABLE "vec_search_chunks_chunks"(chunk_id INTEGER PRIMARY KEY AUTOINCREMENT,size INTEGER NOT NULL,validity BLOB NOT NULL,rowids BLOB NOT NULL);

-- table vec_search_chunks_info
CREATE TABLE "vec_search_chunks_info" (key text primary key, value any);

-- table vec_search_chunks_rowids
CREATE TABLE "vec_search_chunks_rowids"(rowid INTEGER PRIMARY KEY AUTOINCREMENT,id TEXT UNIQUE NOT NULL,chunk_id INTEGER,chunk_offset INTEGER);

-- table vec_search_chunks_vector_chunks00
CREATE TABLE "vec_search_chunks_vector_chunks00"(rowid PRIMARY KEY,vectors BLOB NOT NULL);

-- trigger SearchSources_ad
CREATE TRIGGER SearchSources_ad AFTER DELETE ON SearchSources BEGIN INSERT INTO SearchSources_fts(SearchSources_fts,rowid,Text,Title) VALUES('delete',old.rowid,old.Text,old.Title); END;

-- trigger SearchSources_ai
CREATE TRIGGER SearchSources_ai AFTER INSERT ON SearchSources BEGIN INSERT INTO SearchSources_fts(rowid,Text,Title) VALUES(new.rowid,new.Text,new.Title); END;

-- trigger SearchSources_au
CREATE TRIGGER SearchSources_au AFTER UPDATE OF Text,Title ON SearchSources BEGIN INSERT INTO SearchSources_fts(SearchSources_fts,rowid,Text,Title) VALUES('delete',old.rowid,old.Text,old.Title); INSERT INTO SearchSources_fts(rowid,Text,Title) VALUES(new.rowid,new.Text,new.Title); END;

