-- Generated by Tests/DB/SchemaSnapshotTests.cs from an empty database. Do not edit by hand.
-- Regenerate: set VIBE_RAILS_UPDATE_SCHEMA_SNAPSHOT=1, then: dotnet test Tests --filter SchemaSnapshotTests
-- Every diff in this file is a table change and needs the owner's sign-off (vibe-data/docs/db-migration-policy.md).

-- index idx_agent_metadata_path
CREATE INDEX idx_agent_metadata_path ON AgentMetadata(Path);

-- index idx_compression_captures_created
CREATE INDEX idx_compression_captures_created ON CompressionCaptures(CreatedUTC DESC);

-- index idx_compression_captures_hash
CREATE UNIQUE INDEX idx_compression_captures_hash ON CompressionCaptures(ContentHash) WHERE ContentHash != '';

-- index idx_environment_steps_env
CREATE INDEX idx_environment_steps_env ON EnvironmentSteps(EnvironmentId, Phase, Position);

-- index idx_environments_name_llm
CREATE INDEX idx_environments_name_llm ON Environments(CustomName, LLM);

-- index idx_environments_name_nocase_llm
CREATE UNIQUE INDEX idx_environments_name_nocase_llm ON Environments(CustomName COLLATE NOCASE, LLM);

-- index idx_file_changes_previous_input
CREATE INDEX idx_file_changes_previous_input ON InputFileChanges(PreviousInputId);

-- index idx_input_file_changes_filepath
CREATE INDEX idx_input_file_changes_filepath ON InputFileChanges(FilePath);

-- index idx_input_file_changes_input
CREATE INDEX idx_input_file_changes_input ON InputFileChanges(UserInputId);

-- index idx_job_actions_job
CREATE INDEX idx_job_actions_job ON JobActions(JobId, Position);

-- index idx_job_run_actions_run
CREATE INDEX idx_job_run_actions_run ON JobRunActions(RunId, Position);

-- index idx_job_runs_job
CREATE INDEX idx_job_runs_job ON JobRuns(JobId, QueuedUTC DESC);

-- index idx_job_runs_job_history
CREATE INDEX idx_job_runs_job_history ON JobRuns(JobId, DeletedUTC, QueuedUTC DESC, Id DESC);

-- index idx_job_runs_project_history_nocase
CREATE INDEX idx_job_runs_project_history_nocase ON JobRuns(ProjectPath COLLATE NOCASE, DeletedUTC, JobId, QueuedUTC DESC, Id DESC);

-- index idx_job_runs_queue
CREATE INDEX idx_job_runs_queue ON JobRuns(Status, QueuedUTC);

-- index idx_job_triggers_due
CREATE INDEX idx_job_triggers_due ON JobTriggers(Kind, NextRunUTC);

-- index idx_jobs_project
CREATE INDEX idx_jobs_project ON Jobs(ProjectPath, Enabled, DeletedUTC);

-- index idx_sandboxes_environment
CREATE INDEX idx_sandboxes_environment ON Sandboxes(EnvironmentId);

-- index idx_sandboxes_project
CREATE INDEX idx_sandboxes_project ON Sandboxes(ProjectPath);

-- index idx_session_logs_session
CREATE INDEX idx_session_logs_session ON SessionLogs(SessionId);

-- index idx_session_output_session
CREATE UNIQUE INDEX idx_session_output_session ON sessionOutPut(SessionId);

-- index idx_sessions_retention
CREATE INDEX idx_sessions_retention ON Sessions(EndedUTC,Id) WHERE EndedUTC IS NOT NULL AND ExportedUTC IS NOT NULL;

-- index idx_sessions_started
CREATE INDEX idx_sessions_started ON Sessions(StartedUTC DESC);

-- index idx_sessions_unaggregated
CREATE INDEX idx_sessions_unaggregated ON Sessions(EndedUTC) WHERE AggregateEmbeddedUTC IS NULL AND EndedUTC IS NOT NULL;

-- index idx_sessions_unexported
CREATE INDEX idx_sessions_unexported ON Sessions(EndedUTC, Id) WHERE ExportedUTC IS NULL AND EndedUTC IS NOT NULL;

-- index idx_terminal_session_logs_session
CREATE INDEX idx_terminal_session_logs_session ON TerminalSessionLogs(SessionId, Sequence);

-- index idx_user_inputs_session
CREATE INDEX idx_user_inputs_session ON UserInputs(SessionId);

-- index idx_user_inputs_session_seq
CREATE INDEX idx_user_inputs_session_seq ON UserInputs(SessionId, Sequence);

-- index idx_user_inputs_unembedded
CREATE INDEX idx_user_inputs_unembedded ON UserInputs(Id) WHERE BertEmbeddedUTC IS NULL;

-- table AgentMetadata
CREATE TABLE AgentMetadata ( Id INTEGER PRIMARY KEY AUTOINCREMENT, Path TEXT NOT NULL UNIQUE, CustomName TEXT NOT NULL );

-- table ChatSummary
CREATE TABLE ChatSummary ( Id INTEGER PRIMARY KEY AUTOINCREMENT, SessionId TEXT NOT NULL UNIQUE, SummaryText TEXT NOT NULL DEFAULT '', Date TEXT NOT NULL );

-- table CodeAnalyzerIgnores
CREATE TABLE CodeAnalyzerIgnores ( RepositoryPath TEXT NOT NULL COLLATE NOCASE, Path TEXT NOT NULL COLLATE NOCASE, MatchKind TEXT NOT NULL DEFAULT 'file', ReasonKind TEXT, ReasonText TEXT, CreatedUTC TEXT NOT NULL, PRIMARY KEY (RepositoryPath, Path) );

-- table CompressionCaptures
CREATE TABLE CompressionCaptures ( Id TEXT PRIMARY KEY, CreatedUTC TEXT NOT NULL, Provider TEXT NOT NULL, ToolName TEXT NOT NULL, Command TEXT, RawText TEXT NOT NULL, CompressedText TEXT NOT NULL, CharsBefore INTEGER NOT NULL, CharsAfter INTEGER NOT NULL, Changed INTEGER NOT NULL, RewriteAccepted INTEGER NOT NULL DEFAULT 0, EnabledIds TEXT NOT NULL, Trace TEXT NOT NULL, ContentHash TEXT NOT NULL DEFAULT '', SeenCount INTEGER NOT NULL DEFAULT 1 );

-- table EnvironmentSteps
CREATE TABLE EnvironmentSteps ( Id TEXT PRIMARY KEY, EnvironmentId INTEGER NOT NULL, Phase INTEGER NOT NULL, Position INTEGER NOT NULL, Name TEXT NOT NULL DEFAULT '', Command TEXT NOT NULL, StartMinimized INTEGER NOT NULL DEFAULT 0, TimeoutSeconds INTEGER NOT NULL DEFAULT 600, Enabled INTEGER NOT NULL DEFAULT 1, CreatedUTC TEXT NOT NULL, UpdatedUTC TEXT NOT NULL, FOREIGN KEY (EnvironmentId) REFERENCES Environments(Id) ON DELETE CASCADE );

-- table Environments
CREATE TABLE Environments ( Id INTEGER PRIMARY KEY AUTOINCREMENT, CustomName TEXT NOT NULL, LLM INTEGER NOT NULL, Path TEXT NOT NULL DEFAULT '', CustomArgs TEXT NOT NULL DEFAULT '', CustomPrompt TEXT NOT NULL DEFAULT '', CreatedUTC TEXT NOT NULL, LastUsedUTC TEXT NOT NULL, Hidden INTEGER NOT NULL DEFAULT 0, AutomationWorker INTEGER NOT NULL DEFAULT 0, WorkspaceMode INTEGER NOT NULL DEFAULT 0, ProjectPath TEXT, UNIQUE(CustomName, LLM) );

-- table GlobalCache
CREATE TABLE GlobalCache ( Key TEXT NOT NULL PRIMARY KEY, Value TEXT NOT NULL DEFAULT '', UpdatedUTC TEXT NOT NULL );

-- table InputFileChanges
CREATE TABLE InputFileChanges ( Id INTEGER PRIMARY KEY AUTOINCREMENT, UserInputId INTEGER NOT NULL, PreviousInputId INTEGER, FilePath TEXT NOT NULL, ChangeType TEXT NOT NULL, LinesAdded INTEGER, LinesDeleted INTEGER, DiffContent TEXT, FOREIGN KEY (UserInputId) REFERENCES UserInputs(Id), FOREIGN KEY (PreviousInputId) REFERENCES UserInputs(Id) );

-- table JobActions
CREATE TABLE JobActions ( Id TEXT PRIMARY KEY, JobId INTEGER NOT NULL, Position INTEGER NOT NULL, Kind INTEGER NOT NULL, EnvironmentId INTEGER, ScriptPath TEXT, ScriptRuntime INTEGER, ArgumentsJson TEXT NOT NULL DEFAULT '[]', WorkingDirectory TEXT, TimeoutSeconds INTEGER NOT NULL DEFAULT 0, ApprovedHash TEXT, CreatedUTC TEXT NOT NULL, UpdatedUTC TEXT NOT NULL, FOREIGN KEY (JobId) REFERENCES Jobs(Id) ON DELETE CASCADE, FOREIGN KEY (EnvironmentId) REFERENCES Environments(Id) ON DELETE SET NULL, UNIQUE(JobId, Position) );

-- table JobRunActions
CREATE TABLE JobRunActions ( Id TEXT PRIMARY KEY, RunId TEXT NOT NULL, SourceActionId TEXT, Position INTEGER NOT NULL, Kind INTEGER NOT NULL, Status INTEGER NOT NULL, EnvironmentId INTEGER, EnvironmentName TEXT, Llm INTEGER NOT NULL DEFAULT 0, ScriptPath TEXT, ScriptRuntime INTEGER, ArgumentsJson TEXT NOT NULL DEFAULT '[]', WorkingDirectory TEXT, TimeoutSeconds INTEGER NOT NULL DEFAULT 0, ApprovedHash TEXT, SessionId TEXT, StartedUTC TEXT, EndedUTC TEXT, ExitCode INTEGER, ErrorMessage TEXT, StandardOutput TEXT NOT NULL DEFAULT '', StandardError TEXT NOT NULL DEFAULT '', FOREIGN KEY (RunId) REFERENCES JobRuns(Id) ON DELETE CASCADE, UNIQUE(RunId, Position) );

-- table JobRuns
CREATE TABLE JobRuns ( Id TEXT PRIMARY KEY, JobId INTEGER NOT NULL, TriggerKind INTEGER NOT NULL, TriggerKey TEXT NOT NULL UNIQUE, Status INTEGER NOT NULL, JobName TEXT NOT NULL, ProjectPath TEXT NOT NULL, Llm INTEGER NOT NULL, EnvironmentId INTEGER, EnvironmentName TEXT, TimeoutMinutes INTEGER NOT NULL, SessionId TEXT, QueuedUTC TEXT NOT NULL, StartedUTC TEXT, EndedUTC TEXT, ExitCode INTEGER, ErrorMessage TEXT, CancelRequested INTEGER NOT NULL DEFAULT 0, OwnerProcessId INTEGER, LaunchedUTC TEXT, LaunchMinimized INTEGER NOT NULL DEFAULT 0, DeletedUTC TEXT, LaunchInTerminalTab INTEGER NOT NULL DEFAULT 0, TerminalSessionId TEXT, FOREIGN KEY (JobId) REFERENCES Jobs(Id) );

-- table JobSchedulerLease
CREATE TABLE JobSchedulerLease ( LeaseName TEXT PRIMARY KEY, OwnerId TEXT NOT NULL, ExpiresUTC TEXT NOT NULL );

-- table JobTriggers
CREATE TABLE JobTriggers ( Id INTEGER PRIMARY KEY AUTOINCREMENT, JobId INTEGER NOT NULL, Kind INTEGER NOT NULL, ScheduleKind INTEGER, IntervalMinutes INTEGER, LocalTime TEXT, DaysOfWeekMask INTEGER NOT NULL DEFAULT 0, TimeZoneId TEXT, NextRunUTC TEXT, LastRunUTC TEXT, FOREIGN KEY (JobId) REFERENCES Jobs(Id), UNIQUE(JobId, Kind) );

-- table Jobs
CREATE TABLE Jobs ( Id INTEGER PRIMARY KEY AUTOINCREMENT, Name TEXT NOT NULL, ProjectPath TEXT NOT NULL, EnvironmentId INTEGER, TimeoutMinutes INTEGER NOT NULL DEFAULT 60, Enabled INTEGER NOT NULL DEFAULT 0, LaunchMinimized INTEGER NOT NULL DEFAULT 0, CreatedUTC TEXT NOT NULL, UpdatedUTC TEXT NOT NULL, DeletedUTC TEXT, ImportedFromJobId INTEGER, LaunchInTerminalTab INTEGER NOT NULL DEFAULT 0, FOREIGN KEY (EnvironmentId) REFERENCES Environments(Id) ON DELETE SET NULL );

-- table ProjectCache
CREATE TABLE ProjectCache ( ProjectPath TEXT NOT NULL, Key TEXT NOT NULL, Value TEXT NOT NULL DEFAULT '', UpdatedUTC TEXT NOT NULL, PRIMARY KEY (ProjectPath, Key) );

-- table Sandboxes
CREATE TABLE Sandboxes ( Id INTEGER PRIMARY KEY AUTOINCREMENT, Name TEXT NOT NULL, Path TEXT NOT NULL, ProjectPath TEXT NOT NULL, Branch TEXT NOT NULL DEFAULT '', CommitHash TEXT, RemoteUrl TEXT, SourceBranch TEXT, CreatedUTC TEXT NOT NULL, EnvironmentId INTEGER, UNIQUE(Name, ProjectPath) );

-- table SchemaMigrations
CREATE TABLE SchemaMigrations ( Component TEXT NOT NULL, Version INTEGER NOT NULL CHECK (Version > 0), AppliedUTC TEXT NOT NULL, AppliedBy TEXT, PRIMARY KEY (Component, Version) );

-- table SessionLogs
CREATE TABLE SessionLogs ( Id INTEGER PRIMARY KEY AUTOINCREMENT, SessionId TEXT NOT NULL, Timestamp TEXT NOT NULL, Content BLOB NOT NULL, IsError INTEGER NOT NULL DEFAULT 0, FOREIGN KEY (SessionId) REFERENCES Sessions(Id) );

-- table Sessions
CREATE TABLE Sessions ( Id TEXT PRIMARY KEY, Cli TEXT NOT NULL, EnvironmentName TEXT, WorkingDirectory TEXT NOT NULL, ProjectDisplayName TEXT NOT NULL DEFAULT '', StartedUTC TEXT NOT NULL, EndedUTC TEXT, ExitCode INTEGER, Processed INTEGER NOT NULL DEFAULT 0, ParentSessionId TEXT DEFAULT '', SessionDisplayName TEXT DEFAULT '', OwnerPid INTEGER, OwnershipTracked INTEGER NOT NULL DEFAULT 1, JobRunId TEXT, ExportedUTC TEXT, ExportAttempts INTEGER NOT NULL DEFAULT 0, ExportNextAttemptUTC TEXT , AggregateEmbeddedUTC TEXT, AggregateEmbedFailureCount INTEGER NOT NULL DEFAULT 0, ExportedProxyCoverage TEXT NULL, ExportedProxyMaxRowId INTEGER NULL);

-- table TerminalSessionLogs
CREATE TABLE TerminalSessionLogs ( Id INTEGER PRIMARY KEY AUTOINCREMENT, SessionId TEXT NOT NULL, Sequence INTEGER NOT NULL, IsAlternateScreen INTEGER NOT NULL DEFAULT 0, Data BLOB NOT NULL, Cols INTEGER NOT NULL DEFAULT 80, Rows INTEGER NOT NULL DEFAULT 24, Timestamp TEXT NOT NULL, FOREIGN KEY (SessionId) REFERENCES Sessions(Id) );

-- table TokenSavings
CREATE TABLE TokenSavings ( Day TEXT NOT NULL, Provider TEXT NOT NULL, Requests INTEGER NOT NULL DEFAULT 0, RewrittenRequests INTEGER NOT NULL DEFAULT 0, BytesBefore INTEGER NOT NULL DEFAULT 0, BytesAfter INTEGER NOT NULL DEFAULT 0, UpdatedUTC TEXT NOT NULL, PRIMARY KEY (Day, Provider) );

-- table UserInputSearchDocuments
CREATE TABLE UserInputSearchDocuments ( UserInputId INTEGER PRIMARY KEY REFERENCES UserInputs(Id) ON DELETE CASCADE, InputText TEXT NOT NULL );

-- table UserInputSearchPending
CREATE TABLE UserInputSearchPending ( UserInputId INTEGER PRIMARY KEY REFERENCES UserInputs(Id) ON DELETE CASCADE );

-- table UserInputs
CREATE TABLE UserInputs ( Id INTEGER PRIMARY KEY AUTOINCREMENT, SessionId TEXT NOT NULL, Sequence INTEGER NOT NULL, InputText TEXT NOT NULL, GitCommitHash TEXT, TimestampUTC TEXT NOT NULL, BertEmbeddedUTC TEXT, BertEmbedFailureCount INTEGER NOT NULL DEFAULT 0, FOREIGN KEY (SessionId) REFERENCES Sessions(Id) );

-- table UserInputs_fts
CREATE VIRTUAL TABLE UserInputs_fts USING fts5( InputText, content='UserInputSearchDocuments', content_rowid='UserInputId', tokenize='porter unicode61' );

-- table UserInputs_fts_config
CREATE TABLE 'UserInputs_fts_config'(k PRIMARY KEY, v) WITHOUT ROWID;

-- table UserInputs_fts_data
CREATE TABLE 'UserInputs_fts_data'(id INTEGER PRIMARY KEY, block BLOB);

-- table UserInputs_fts_docsize
CREATE TABLE 'UserInputs_fts_docsize'(id INTEGER PRIMARY KEY, sz BLOB);

-- table UserInputs_fts_idx
CREATE TABLE 'UserInputs_fts_idx'(segid, term, pgno, PRIMARY KEY(segid, term)) WITHOUT ROWID;

-- table sessionOutPut
CREATE TABLE sessionOutPut ( Id INTEGER PRIMARY KEY AUTOINCREMENT, SessionId TEXT NOT NULL, Text TEXT NOT NULL, FOREIGN KEY (SessionId) REFERENCES Sessions(Id) ON DELETE CASCADE );

-- table sqlite_sequence
CREATE TABLE sqlite_sequence(name,seq);

-- trigger Sessions_LinkJobRunSession
CREATE TRIGGER Sessions_LinkJobRunSession AFTER INSERT ON Sessions WHEN NEW.JobRunId IS NOT NULL BEGIN UPDATE JobRuns SET SessionId = NEW.Id WHERE Id = NEW.JobRunId AND DeletedUTC IS NULL; SELECT RAISE(ABORT, 'The Job run for this terminal session no longer exists.') WHERE changes() <> 1; END;

-- trigger UserInputSearchDocuments_ad
CREATE TRIGGER UserInputSearchDocuments_ad AFTER DELETE ON UserInputSearchDocuments BEGIN INSERT INTO UserInputs_fts(UserInputs_fts,rowid,InputText) VALUES('delete',old.UserInputId,old.InputText); END;

-- trigger UserInputSearchDocuments_ai
CREATE TRIGGER UserInputSearchDocuments_ai AFTER INSERT ON UserInputSearchDocuments BEGIN INSERT INTO UserInputs_fts(rowid, InputText) VALUES(new.UserInputId, new.InputText); END;

-- trigger UserInputSearchDocuments_au
CREATE TRIGGER UserInputSearchDocuments_au AFTER UPDATE ON UserInputSearchDocuments BEGIN INSERT INTO UserInputs_fts(UserInputs_fts,rowid,InputText) VALUES('delete',old.UserInputId,old.InputText); INSERT INTO UserInputs_fts(rowid,InputText) VALUES(new.UserInputId,new.InputText); END;

-- trigger UserInputs_fts_ad
CREATE TRIGGER UserInputs_fts_ad AFTER DELETE ON UserInputs BEGIN DELETE FROM UserInputSearchDocuments WHERE UserInputId=old.Id; DELETE FROM UserInputSearchPending WHERE UserInputId=old.Id; END;

-- trigger UserInputs_search_ai
CREATE TRIGGER UserInputs_search_ai AFTER INSERT ON UserInputs BEGIN INSERT OR IGNORE INTO UserInputSearchPending(UserInputId) VALUES(new.Id); END;

-- trigger UserInputs_search_au
CREATE TRIGGER UserInputs_search_au AFTER UPDATE OF InputText ON UserInputs WHEN old.InputText IS NOT new.InputText BEGIN DELETE FROM UserInputSearchDocuments WHERE UserInputId=old.Id; INSERT OR IGNORE INTO UserInputSearchPending(UserInputId) VALUES(new.Id); END;

